name: Build and Release

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-14]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up build environment
        run: |
          brew install gnu-sed

      - name: Build BusyBox
        run: |
          cp configs/osx_defconfig .config
          make LLVM=1 -j$(nproc)

      - name: Upload BusyBox executable
        uses: actions/upload-artifact@v4
        with:
          name: busybox-${{ matrix.os }}
          path: busybox